// <auto-generated />
namespace TeamManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatePlayerButtons : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatePlayerButtons));
        
        string IMigrationMetadata.Id
        {
            get { return "201801162008262_updatePlayerButtons"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
